package com.example.drainagemonitoring.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.me.pipelinedetectionapp.bean.DetectionDb;
import com.me.pipelinedetectionapp.bean.PipePSCheckDb;
import com.me.pipelinedetectionapp.bean.ProjectDb;

import com.example.drainagemonitoring.greendao.DetectionDbDao;
import com.example.drainagemonitoring.greendao.PipePSCheckDbDao;
import com.example.drainagemonitoring.greendao.ProjectDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig detectionDbDaoConfig;
    private final DaoConfig pipePSCheckDbDaoConfig;
    private final DaoConfig projectDbDaoConfig;

    private final DetectionDbDao detectionDbDao;
    private final PipePSCheckDbDao pipePSCheckDbDao;
    private final ProjectDbDao projectDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        detectionDbDaoConfig = daoConfigMap.get(DetectionDbDao.class).clone();
        detectionDbDaoConfig.initIdentityScope(type);

        pipePSCheckDbDaoConfig = daoConfigMap.get(PipePSCheckDbDao.class).clone();
        pipePSCheckDbDaoConfig.initIdentityScope(type);

        projectDbDaoConfig = daoConfigMap.get(ProjectDbDao.class).clone();
        projectDbDaoConfig.initIdentityScope(type);

        detectionDbDao = new DetectionDbDao(detectionDbDaoConfig, this);
        pipePSCheckDbDao = new PipePSCheckDbDao(pipePSCheckDbDaoConfig, this);
        projectDbDao = new ProjectDbDao(projectDbDaoConfig, this);

        registerDao(DetectionDb.class, detectionDbDao);
        registerDao(PipePSCheckDb.class, pipePSCheckDbDao);
        registerDao(ProjectDb.class, projectDbDao);
    }
    
    public void clear() {
        detectionDbDaoConfig.clearIdentityScope();
        pipePSCheckDbDaoConfig.clearIdentityScope();
        projectDbDaoConfig.clearIdentityScope();
    }

    public DetectionDbDao getDetectionDbDao() {
        return detectionDbDao;
    }

    public PipePSCheckDbDao getPipePSCheckDbDao() {
        return pipePSCheckDbDao;
    }

    public ProjectDbDao getProjectDbDao() {
        return projectDbDao;
    }

}
